### ISSUE TITLE
Cache: Front-end API similar to Block IO

### ISSUE THREAD

**Issue by m-stein** [cbe-project/cbe#46]
The cache module does currently not follow the common approach for module APIs in the CBE. Instead of submitting a primitive at the cache, other modules poll for the required PBAs on the cache object. The modules then access the cache entries directly and also have to mark written cache entries "dirty" themselves. Furthermore, the cache cannot evict dirty entries by flushing them. Dirty entries become clean again only when the separate cache-flusher module does a flush of all dirty entries (done only when syncing, creating a snapshot, or the like). There are also modules other then the cache and the cache-flusher that access block-io for CBE metadata directly.

I'd aim for a cache module that has the same front end as the block-io module. A cache entry is guaranteed to be in the cache only as long as there are pending cache primitives for the entry. A cache user would receive the cache index of read data through Cache.Peek_Completed_Primitive and would denote that he's done with processing the corresponding entry via Cache.Drop_Completed_Primitive. Written data is communicated using the cache index returned by Cache.Submit_Primitive. This way, cache users would have to either store a copy of cache data they want to use throughout multiple cycles of the CBE or directly write it back and re-request it later. Furthermore, I would merge the cache flusher into the cache and let the cache evict dirty entries by flushing them selectively. The internals of the cache could be simplified by merging job-items and the entry-items.

Modules other than the cache would not access the block io for metadata anymore. A second instance of the new cache module could be used for leaf data, so, caches are the only ones accessing block io in general. And they would be functionally transparent. I.e. one could easily deactivate caches for debugging purposes.

My migration path is the following:

* Remove direct use of cache from modules (VBD, Free Tree) and modify them in a way that they access the cache in the same way they would access Block IO. The arbiter (Library) translates these new access attempts to the old cache API.
* Remove cache completely from arbiter (Library) and let all modules access Block IO instead of the cache.
* Implement new cache. Integration of new cache should now be easy.

**Comment by m-stein** [comment]
On my branch cbe_cache I could finish the first two steps. However, the last change of the second step causes a hash mismatch after having successfully finished several client requests.

@cnuke I wonder whether the CBE internals assume at some point that data is not directly written to block IO (i.e., the old version is still accessed directly via Block IO, or the new version is not yet ready to be written out)?

396eddb (HEAD -> cbe_cache, mstein/cbe_cache) RUNTIME ERRORS "cbe: do not use cache in Library"
9d90e17 cbe: move Supply_Client_Data code to Execute
4fd8edb cbe: do not use cache in free tree
8cf38fa cbe: VBD.Peek_Generated_Cache_Data
526b643 cbe: remove unnecessary WB phase in Free_Tree
8a5545f cbe_init: remove unused files
eb5def2 cbe.run: always re-build all Ada sources
733e1a0 cbe: do not use cache in Free_Tree.Update_Inner* and .Exchange_PBA*
466530a cbe: do not use cache in Free_Tree.Execute_Translation
fca04c2 cbe: do not use cache in Free_Tree.Execute_Query
15d1afe cbe: easier state structure in Free_Tree.Execute and state debugging output
17c8ca7 Revert "cbe: do not use cache in free tree (part 2, first try)"
b08d0e7 cbe: do not use cache in free tree (part 2, first try part 2)
c2feae1 cbe: do not use cache in free tree (part 2, first try part 1)
49361e0 cbe: do not use cache in free tree (part 1, translation generated prims)
5fd9490 cbe: do not use cache in VBD
4bc7443 cbe-library: unused function Cache_Dirty
f191f90 cbe.gpr: add lib/cbe_common as source dir

**Comment by cnuke** [comment]
@m-stein I don't know, you have me at a loss here. At least direct block I/O should be easy to spot.

**Comment by m-stein** [comment]
@cnuke That's true! I'll track it down then.

**Comment by m-stein** [comment]
In the end removing the cache from the arbiter wasn't as easy as I thought even after having it removed from the other modules. There is still a significant amount of logic in the arbiter that should move to the modules ^^

**Comment by cnuke** [comment]
Yeah :-/

**Comment by m-stein** [comment]
It's working now without cache at all :)
I forgot to store some state from function to object scope when transitioning from a function that runs through in one call to a function that needs to be called several times to get done.
I'm happy that I can finally proceed with implementing the new cache.

**Comment by cnuke** [comment]
@m-stein commit fdafdb36c5 adds the discussed automatic eviction. It is far from perfect, e.g. `Write_Back_Dirty_Slot` might be called multiple times even if only on Job is pending, which in return could raise the exception if there is no dirty slot left, but with it my vfs_replay test finally succeeds.

**Comment by m-stein** [comment]
@cnuke Thanks for having investigated this problem so persistently! I like your patch very much and merely made some minor adaptions:
* ``To_String`` functions for enumeration types aren't necessary as I just found out. One can use the built-in ``'Image`` attribute instead [[1](https://en.wikibooks.org/wiki/Ada_Programming/Types/Enumeration#Operators_and_attributes)]: ``Debug.Print_String (Slots (Idx).State'Image);``.
* I fixed the problem of multiple write-back-ops with only one job by starting a write-back only when there's yet no write-back in progress. I aware that this serializes such operations even when there are multiple pending jobs but I think this is fine for now.
* I simplified the code in the write-back procedure a bit.

With the ``cbe_tester.run`` script, I can now run a lot more tests successfully and I see that the cache writes back as expected.

However, when further raising the amount of tests there is a point where the CBE still gets stuck (on my cbe_rekeying branch and on your cbe_wip-cache branch with your cache patch reverted and 0f5d440 0ee52e7 applied instead). The last thing I see at the Pool module is a call to Peek_Generated_VBD_Primitive.

**Comment by cnuke** [comment]
@m-stein thanks, your changes are pretty much inline with what I had in mind as well. And especially thanks for pointing out `'Image` to me again - I completely crossed that from my mind as at some point we were lacking some parts in the runtime that prevented its usage on certain types.

Regarding still getting stuck, I mentioned that there mutliple ways in which the CBE might get stuck, cache write-back is probably just on the issues. I'll check if I can reproduce your problem with the VFS as well.

**Comment by cnuke** [comment]
Using an adapted (no snapshot creation!) test (see c0331b10f8) with the `vfs_replay` component and the CBE VFS plugin works fine. However, when the test is performed multiple times using the same underlying CBE disk image, i.e. the image is only initialized once, eventually the test gets stuck when the CBE is processing a `SYNC` request.

**Comment by m-stein** [comment]
This issue is fixed in the 20.05 release.
